### ISSUE TITLE
How can I perform an upload request ?

### ISSUE THREAD

**Issue by theophpo** [alchemy-fr/phrasea#200]
Hello, I'm currently working on Phrasea for doing a file indexing 

I want to perform an upload using the Phrasea uploader api, is there a high level way to perform an upload?
(https://github.com/alchemy-fr/phrasea/blob/master/uploader/doc/sequence.png)
I saw that the documentation explains how to use assets and commits, can you tell us more? Is there a high level upload request ?

Thanks in advance.

**Comment by 4rthem** [comment]
Hello,
Yes Uploader API can be call directly. Unfortunately there is no documentation about this but you can take a look at the [Uploader client multipart upload](https://github.com/alchemy-fr/phrasea/blob/master/uploader/client/src/multiPartUpload.js).
